[package]
name = "ezmenu"
version = "0.2.0"
edition = "2021"
authors = ["Ahmad Baalbaky <ahmad@salondesdevs.fr>"]
documentation = "https://docs.rs/ezmenu"
description = "Builds a CLI menu with a derive."
repository = "https://github.com/ahbalbk/ezmenu"
categories = ["command-line-interface"]
license = "MIT"
readme = "README.md"
exclude = [
    "tests/*"
]

[features]
custom_io = ["ezmenu-derive/custom_io"]

[[test]]
name = "base_impl"
path = "tests/base_impl.rs"
required-features = ["custom_io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezmenu-derive = { path = "ezmenu-derive", version = "0.2.0"}
