[package]
name = "ezmenulib"
version = "0.3.0"
edition = "2021"
authors = ["Ahmad Baalbaky <ahmad@salondesdevs.fr>"]
documentation = "https://docs.rs/ezmenulib"
description = "Easy CLI menu building tool."
repository = "https://github.com/ahbalbk/ezmenulib"
categories = ["command-line-interface"]
keywords = ["cli", "menu", "interface"]
license = "MIT"
readme = "README.md"
exclude = [
    "tests/*"
]

[lib]
name = "ezmenulib"

[package.metadata.docs.rs]
all-features = true

[dependencies.meval]
version = "0.2.0"
optional = true
default-features = false 

[dependencies.crossterm]
version = "0.23.2"
optional = true
default-features = false

[dependencies.cursive]
version = "0.18.0"
optional = true
default-features = false

[dependencies.termion]
git = "https://github.com/ahbalbk/termion"
branch = "mouse_cmds"
optional = true
default-features = false

[dependencies.tui]
git = "https://github.com/ahbalbk/tui-rs"
branch = "backend_deref"
optional = true
default-features= false

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = []
expr = ["dep:meval"]
crossterm = ["dep:crossterm", "tui?/crossterm"]
termion = ["dep:termion", "tui?/termion"]
c-crossterm = ["cursive?/crossterm-backend"]
c-termion = ["cursive?/termion-backend"]
c-ncurses = ["cursive?/ncurses-backend"]
c-pancurses = ["cursive?/pancurses-backend"]
c-blt = ["cursive?/blt-backend"]

[[example]]
name = "tui_menu"
required-features = ["tui", "crossterm"]