[package]
name = "ezmenu"
version = "0.1.0"
edition = "2021"
authors = ["Ahmad Baalbaky <ahmad@salondesdevs.fr>"]
documentation = "https://docs.rs/ezmenu-derive"
description = "Builds a CLI menu with a derive."
repository = "https://github.com/ahbalbk/ezmenu"
categories = ["command-line-interface"]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezmenu-derive = { version = "0.1.0", path = "./ezmenu-derive" }
