[package]
name = "ezmenulib"
version = "0.3.0"
edition = "2021"
authors = ["Ahmad Baalbaky <ahmad@salondesdevs.fr>"]
documentation = "https://docs.rs/ezmenulib"
description = "Build easily a CLI menu."
repository = "https://github.com/ahbalbk/ezmenulib"
categories = ["command-line-interface"]
keywords = ["cli", "menu", "interface"]
license = "MIT"
readme = "README.md"
exclude = [
    "tests/*"
]

[lib]
name = "ezmenulib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"

# Optional dependencies:
meval = { version = "0.2.0", optional = true, default-features = false }
termion = {version = "1.5.0", optional = true, default-features = false }
crossterm = { version = "0.23.2", optional = true, default-features = false }
tui = { version = "0.18.0", optional = true, default-features = false }
cursive = { version = "0.18.0", optional = true, default-features = false }

[features]
expr = ["dep:meval"]
crossterm = ["dep:crossterm", "tui?/crossterm"]
termion = ["dep:termion", "tui?/termion"]