[package]
name = "ezmenulib"
version = "0.3.0"
edition = "2021"
authors = ["Ahmad Baalbaky <ahmad@salondesdevs.fr>"]
documentation = "https://docs.rs/ezmenulib"
description = "Build easily a CLI menu."
repository = "https://github.com/ahbalbk/ezmenulib"
categories = ["command-line-interface"]
keywords = ["cli", "menu", "interface"]
license = "MIT"
readme = "README.md"
exclude = [
    "tests/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"

# Optional dependencies:
meval = { version = "0.2.0", optional = true }
crossterm = { version = "0.23.2", optional = true }
tui = { version = "0.18.0", optional = true }

[dependencies.cursive]
version = "0.18.0"
default-features = false
features = ["crossterm-backend"]
optional = true

[features]
default = ["expr"]
expr = ["meval"]
i-tui = ["tui", "crossterm"]
i-cursive = ["cursive"]